[versions]
agp = "7.2.2"
kotlin = "1.8.10"
kotlinDatetime = "0.4.0"
ksp = "1.7.10-1.0.6"
material = "1.6.1"
compose = "1.4.0-rc01"
composeCompiler = "1.4.3"
jvmTarget = "1.8"
androidxActivity = "1.6.0"
androidxFragment = "1.5.1"
androidxLifecycle = "2.5.1"
androidxRoom = "2.4.3"
androidxNavigation = "2.5.1"
androidxArchCore = "2.1.0"
androidXStartup = "1.1.1"
androidXKtx = "1.9.0"
recyclerView = "1.2.1"
okHttp = "4.10.0"
hilt = "2.43.2"
hiltNavigation = "1.0.0"
hiltAndroidCompiler = "1.0.0"
retrofit = "2.9.0"
coroutines = "1.6.4"
glide = "4.13.2"
macroBenchmark = "1.1.0"
timber = "5.0.1"
baselineProfiles = "1.2.0"
junit = "4.13.2"
turbine = "0.6.0"
robolectric = "4.4"
androidxTest = "1.3.0"
androidxTestJunit = "1.1.2"
androidTestRunner = "1.3.0-beta01"
mockitoKotlin = "2.2.0"
mockitoInline = "3.5.13"
kotlinCompilerExtensionVersion = "1.3.2"
kotlinSerialization = "1.4.1"
kotlinSerializationConverter = "0.8.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
spotless = { id = "com.diffplug.spotless", version = "6.7.2" }
hilt-plugin = { id = "dagger.hilt.android.plugin", version = "hilt" }


[libraries]
compose = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigation" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation" }
compose-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }

agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinDatetime" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }
kotlin-serializationPlugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "kotlinSerializationConverter" }
ksp = { module = "com.google.devtools.ksp:symbol-processing", version.ref = "ksp" }
material = { module = "com.google.android.material:material", version.ref = "material" }
fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragment" }
lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidxRoom" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidxRoom" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidxRoom" }
arch-core = { module = "androidx.arch.core:core-testing", version.ref = "androidxArchCore" }
startup = { module = "androidx.startup:startup-runtime", version.ref = "androidXStartup" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidXKtx" }
test-core = { module = "androidx.test:core", version.ref = "androidxTest" }
android-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestJunit" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
retrofit = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttp" }
okhttp-mockserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okHttp" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerView" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# unit test
junit = { module = "junit:junit", version.ref = "junit" }
mockito-kotlin = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockitoKotlin" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
android-test-runner = { module = "com.android.support.test:runner", version.ref = "androidTestRunner" }
profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "baselineProfiles" }
macrobenchmark = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "macroBenchmark" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-test-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }

[bundles]
compose = [
    "compose",
    "compose-preview",
    "compose-material",
    "compose-ui-tooling-preview",
    "compose-navigation",
    "activity-compose",
    "compose-ui-test",
    "compose-test-tooling",
    "compose-test-manifest",
    "compose-hilt-navigation"
]