name: Deploy debug apk

on:
  push:
    branches:
      - main
      - develop
  repository_dispatch:
    types: [BUILD_APK]

jobs:
  generate-apk:
    name: Generate and deploy debug apk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Execute Gradle Build
        run: ./gradlew assembleDebug

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install slack_sdk

      - id: upload
        name: Upload to Slack
        env: 
          ANDROID_SLACK_BOT_TOKEN: ${{ secrets.ANDROID_SLACK_BOT_TOKEN }}
          CURRENT_BRANCH: ${{ github.ref_name }}
        run: 
          echo ::set-output name=permalink::$(python deploy.py)
        
      - name: Send permalink
        run:
          echo @@@permalink is ${{ steps.upload.outputs.permalink }}
          
